"""Make dog_id nullable in event_registrations

Revision ID: 7a6218d21406
Revises: 75b0da93df76
Create Date: 2025-10-05 21:39:03.039581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a6218d21406'
down_revision = '75b0da93df76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.alter_column('dog_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.alter_column('dog_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
